### ISSUE TITLE
Latest tag fails to create release

### ISSUE THREAD

**Issue by Auburn** [fregante/release-with-changelog#52]
Getting an error with the latest tag, although the action step still reports success. The release is not created.

`Download action repository 'fregante/release-with-changelog@v3' (SHA:304ef3a41972f031ea67fa705ed37a811f37d1b1)`

```Run fregante/release-with-changelog@v3
  with:
    token: ***
    exclude: ^Update\s\S+\.(md|yml)$
    tag: v0.9.4-alpha
    draft: true
    template: ### Changelog
  
  {commits}
  
  {range}
  
    commit-template: - {hash} {title}
    date-format: short
    sort: desc
    prerelease: false
    skip-on-empty: false
(node:1621) Warning: require() of ES modules is not supported.
require() of /home/runner/work/_actions/fregante/release-with-changelog/v3/distribution/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/_actions/fregante/release-with-changelog/v3/package.json.
(node:1621) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setFailed' of undefined
    at run (/home/runner/work/_actions/fregante/release-with-changelog/v3/distribution/index.js:323:17)
    at Module.52 (/home/runner/work/_actions/fregante/release-with-changelog/v3/distribution/index.js:327:1)
    at __webpack_require__ (/home/runner/work/_actions/fregante/release-with-changelog/v3/distribution/index.js:24:31)
    at startup (/home/runner/work/_actions/fregante/release-with-changelog/v3/distribution/index.js:43:19)
    at /home/runner/work/_actions/fregante/release-with-changelog/v3/distribution/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/fregante/release-with-changelog/v3/distribution/index.js:52:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
(node:1621) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1621) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by Auburn** [comment]
OS: ubuntu-latest (20.04)

**Comment by fregante** [comment]
Thanks for the report and sorry. ESM is a f'n PITA. I was fooled by the supposed "support" of this: https://github.com/vercel/ncc/issues/236

I'm releasing another version
